-- CONSTRAINT

USE KISITLAYICILAR

--Kitap Tablosu
CREATE TABLE KITAP
(
ID int,
KITAP_AD VARCHAR(50),
KITAP_YIL DATE,
YAZAR_ID int,
KONUSU VARCHAR(100),
SAYFA_SAYISI int
)
--Yazar tablosu
CREATE TABLE YAZAR
(
ID int,
YAZAR_ADI VARCHAR(50)
)

--kütüphane tablosu
create table KUTUPHANE(
ID int,
KUTUPHANE_ADI VARCHAR(50))

--PERSONEL tABLOSU
CREATE TABLE PERSONEL(
ID int Primary Key Identity(1,1),
PERSONEL_ADI VARCHAR(50),
DEPARTMAN_ID int
)

--DEPARTMAN TABLOSU
CREATE TABLE DEPARTMAN(
DEPARTMAN_ID int primary key identity(1,1),
DEPARTMAN_ADÝ VARCHAR(50)
)



--Primary Key CONSTRAINT

Alter table KITAP
ADD CONSTRAINT PK_ID PRIMARY KEY (ID)

Alter table YAZAR
ADD CONSTRAINT PK_YAZAR_ID PRIMARY KEY (ID)

-- FOREIGN KEY  CONSTRAINT

ALTER TABLE KITAP
ADD CONSTRAINT FK_YAZARID
FOREIGN KEY (YAZAR_ID)
REFERENCES YAZAR(ID)

ALTER TABLE KITAP ADD KUTUPHANE_ID int

ALTER TABLE KITAP
ADD CONSTRAINT FK_KUTUPHANE_ID
FOREIGN KEY (KUTUPHANE_ID)
REFERENCES KUTUPHANE(ID)

ALTER TABLE KITAP
ADD CONSTRAINT FK_KUTUPHANE_ID
FOREIGN KEY (KUTUPHANE_ID)
REFERENCES KUTUPHANE(ID)

ALTER TABLE PERSONEL
ADD CONSTRAINT FK_DEPARTMAN_ID
FOREIGN KEY (DEPARTMAN_ID)
REFERENCES DEPARTMAN(DEPARTMAN_ID) -- REFERENCE ALINAN SÜTUN

-- DEFAULT CONSTRAINT

alter table KITAP
ADD CONSTRAINT DF_YAYIN_EVI --CONSTRAINT ADI
DEFAULT 'ABC YAYINEVÝ'
FOR YAYIN_EVI -- DEFAULT UYGULANAN SÜTUN

ALTER TABLE KITAP
ADD PUAN int
ALTER TABLE KITAP
ADD CONSTRAINT DF_PUAN
DEFAULT 0 FOR PUAN

-- UNIQUE CONSTRAINT

ALTER TABLE KITAP
ADD CONSTRAINT QU_KITAP_AD
UNIQUE (KITAP_AD)

ALTER TABLE KITAP
ADD CONSTRAINT QU_KONUSU
UNIQUE (KONUSU)

--CHECK
alter table KITAP
ADD CONSTRAINT CHK_PUAN
CHECK (PUAN<10 AND PUAN>0)