 /*EXIST/ NOT EXIST ÝÇÝNDE BULUNUYORSA/ÝÇÝNDE BULUNMUYORSA TRUE YA DA FALSE DÖNER
 KOMPLEKS YAPILARDA IN VE NOT IN YERÝNE KULLANILIR. pERFORMANSLIDIR. ýN ÝSE HER TABLOYU OKUMAYA ÇALIÞIR.
 */

 SELECT * FROM Products P
 WHERE EXISTS (SELECT 1 FROM [Order Details] O  WHERE O.ProductID=P.ProductID)