--SUBQUERY



--AVG => ORTALAMA HESAPLAMA

SELECT avg(UnitPrice) FROM [Order Details] --satýþlarýn ortalamasý

SELECT avg(UnitPrice),AVG(Quantity) FROM [Order Details]

--count-sayar
select count(*) from [Order Details]

select count(distinct ordDt.OrderID )from [Order Details] ordDt
where ordDt.OrderID=10248
order by 1 -- tekrar etmeyen order ýd distinct ile.

--COUNT(BIG) -- COUNT BELLÝ SAYIYA KADAR TOPLAR COUNT_BIG ÇOK BÜYÜK TOPLAMLARDA KULLANILIR.

SELECT COUNT_BIG(*) FROM [Order Details]

--SUM ÝNT,NUMERÝC,DECÝMAL TOPLAMA ÝÞLEMÝNÝ YAPAR.
SELECT SUM(Quantity) FROM [Order Details]

--CEILING => BÝR ÜST EN YAKIN TAM SAYI YA YUVARLAR.

SELECT CEILING(2.1)

--FLOOR=> BÝR ALT EN YAKIN TAM SAYIYA YUVARLAR.

SELECT  FLOOR(3.8)

--ROUND(SAYI,ÝNDEX) YUVARLANACAK SAYININ . DAN SONRAKÝ SIRASI=> YUKARI YUVARLAR ÝNDEX 0 DÝKKAT
SELECT ROUND(3.5486,3) -- =>3.5490

-- ASCII => ASCII KPODUNU VERÝR.
SELECT ASCII('C')

--RAND() 0,XXXXXX GÝBÝ BÝR SAYI ÜRETÝR.
SELECT RAND()

--1ÝLE 10 ARASINDA X,XXXXX

SELECT CONVERT(INT,RAND()*10)

--NEWID() EÞSÝZ ALAN VERÝR

SELECT NEWID()

--GETDATE

SELECT COnVERT(date,GETDATE()) --2021-12-28

--convert and cast

select CONVERT(INT,'25')

SELECT CAST(25 AS VARCHAR(2))

SELECT CONVERT(NVARCHAR(10),CAST(25 AS VARCHAR(2)))

--CHARINDEX =>KARAKTER ARAMA KAÇINCI ÝNDEX DE OLDUÐUNU VERÝR. CHARINDEX('ARANACAK KARAKTER','ARANAN METÝN',BAÞLANGIÇ ÝNDEKSÝ)

SELECT CHARINDEX('S','ALÝS',1)

SELECT FirstName,+' '+LastName,
CHARINDEX('L',FirstName+' '+LastName,1)FROM Employees

--LEFT-RÝGHT - SOLDAN YA DA SAÐDAN KAÇ KARATER ALINACAÐI BELÝRLER.

SELECT LEFT(FirstName,3),FirstName FROM Employees

--LEN => KARAKTER BIOYUTU

SELECT LEN(FirstName),FirstName FROM Employees

--RTRÝM,LTRIM,TRIM =>BOÞÞLUUKLARI SÝLER BAÞ VE SON

--REVERSE( ) METNÝN TERSÝNÝ YAZAR.

--UPPER('METÝN') BÜYÜK HARFE LOWER('METÝN') KÜÇÜK HARFE ÇEVÝR.

--SUBSTRÝNG =>METNÝN BAÞLANGIÇ VE BÝTÝÞ ÝNDEKSÝNDEN ÝTÝBAREN ALIR.

SELECT SUBSTRING('ARÝF',1,3)

--REPLACE() ÝSTENÝLEN KARAKTERÝ ÝSTENÝLEN KARAKTERLE DEÐÝÞTÝRÝR.
SELECT REPLACE('AAA VVVVVVV BB CCCCCCCC',' ','')









