--Transaction => Bütün bir bloðu tek bir iþlem gibi sql e söyler. Baþarýlý olmasýný bize söyler.

BEGIN TRAN -- VEYA BEGIN TRANSACTÝON
	INSERT INTO HESAPLAR VALUES(5,'tEST 1','tEST 2',10);
	COMMIT TRANSACTION
	BEGIN TRY
		BEGIN TRAN
			INSERT INTO HESAPLAR VALUES(5,'tEST 1','tEST 2',8);
			COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		PRINT 'hATA: '+ERROR_MESSAGE();
		ROLLBACK TRANSACTION;
	END CATCH